# Generated by Django 3.2.6 on 2023-04-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230422_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Entered_By',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Changed_Date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Changed_Time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='created_Date',
            field=models.CharField(blank=True, default='2023-04-29', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='created_Time',
            field=models.CharField(blank=True, default='13:15:13', max_length=30, null=True),
        ),
    ]
