from django.db import models

# Create your models here.



class UserData(models.Model):
    # CrowdId = models.CharField(max_length=8, primary_key=True)
    Group1 = models.CharField(max_length=12, null=True, blank=True)
    Group2 = models.CharField(max_length=12, null=True, blank=True)
    Group3 = models.CharField(max_length=12, null=True, blank=True)
    Group4 = models.CharField(max_length=12, null=True, blank=True)
    Group5 = models.CharField(max_length=12, null=True, blank=True)
    Group6 = models.CharField(max_length=12, null=True, blank=True)
    Group7 = models.CharField(max_length=12, null=True, blank=True)
    Group8 = models.CharField(max_length=12, null=True, blank=True)
    Group9 = models.CharField(max_length=12, null=True, blank=True)
    Group10 = models.CharField(max_length=12, null=True, blank=True)
    Salutation = models.CharField(max_length=4, null=True, blank=True)
    First_Name = models.CharField(max_length=40, null=True, blank=True)
    Middle_Name = models.CharField(max_length=40, null=True, blank=True)
    Last_Name = models.CharField(max_length=40, null=True, blank=True)
    Primary_Number = models.CharField(max_length=20, null=True, blank=True)
    Alternate_Number = models.CharField(max_length=20, null=True, blank=True)
    Primary_Mail = models.CharField(max_length=80, null=True, blank=True)
    Alternate_Mail = models.CharField(max_length=80, null=True, blank=True)
    Location = models.CharField(max_length=30, null=True, blank=True)
    City = models.CharField(max_length=30, null=True, blank=True)
    State = models.CharField(max_length=30, null=True, blank=True)
    Country = models.CharField(max_length=30, null=True, blank=True)
    Pincode = models.CharField(max_length=8, null=True, blank=True)
    Designation = models.CharField(max_length=40, null=True, blank=True)
    Primary_Expertise = models.CharField(max_length=30, null=True, blank=True)
    Primary_Expertise1 = models.CharField(max_length=30, null=True, blank=True)
    Primary_Expertise2 = models.CharField(max_length=30, null=True, blank=True)
    Highest_Education = models.CharField(max_length=40, null=True, blank=True)
    Gender = models.CharField(max_length=6, null=True, blank=True)
    DOB = models.CharField(max_length=6,null=True, blank=True)
    Message_Open = models.CharField(max_length=1, null=True, blank=True)
    Responded = models.CharField(max_length=1, null=True, blank=True)
    Linked_Clicked = models.CharField(max_length=1, null=True, blank=True)
    Source = models.CharField(max_length=30, null=True, blank=True)
    Org_Name = models.CharField(max_length=40, null=True, blank=True)
    Nature_Of_Business = models.CharField(max_length=120, null=True, blank=True)
    Org_Name_Location = models.CharField(max_length=20, null=True, blank=True)
    Do_Not_Call = models.CharField(max_length=1, null=True, blank=True)
    Do_Not_Message = models.CharField(max_length=1, null=True, blank=True)
    Do_Not_Mail = models.CharField(max_length=1, null=True, blank=True)
    Do_Not_Whatsapp = models.CharField(max_length=1, null=True, blank=True)
    Do_Not_Disturb = models.CharField(max_length=1, null=True, blank=True)
    Notes1 = models.CharField(max_length=120, null=True, blank=True)
    Notes2 = models.CharField(max_length=120, null=True, blank=True)
    Notes3 = models.CharField(max_length=120, null=True, blank=True)
    Notes4 = models.CharField(max_length=120, null=True, blank=True)
    Notes5 = models.CharField(max_length=120, null=True, blank=True)
    Remarks = models.CharField(max_length=500, null=True, blank=True)
    Document_Attach = models.ImageField(upload_to='DocumentAttach/', null=True, blank=True)
    Called = models.CharField(max_length=1, null=True, blank=True)
    Met = models.CharField(max_length=1, null=True, blank=True)
    Full_Name = models.CharField(max_length=100, null=True, blank=True)
    Out_Of_Station = models.CharField(max_length=1, null=True, blank=True)
    Out_Of_Country = models.CharField(max_length=1, null=True, blank=True)
    Generated_Pincode = models.CharField(max_length=8, null=True, blank=True)
    Mark_For_Deletion = models.CharField(max_length=1, null=True, blank=True)
    Reason_For_Deletion = models.CharField(max_length=30, null=True, blank=True)
    Blog_Link = models.CharField(max_length=100, null=True, blank=True)
    Website = models.CharField(max_length=100, null=True, blank=True)
    Linkedin_Link = models.CharField(max_length=100, null=True, blank=True)
    Instagram_Link = models.CharField(max_length=100, null=True, blank=True)
    Youtube_Link = models.CharField(max_length=100, null=True, blank=True)
    Facebook_Link = models.CharField(max_length=100, null=True, blank=True)
    Social_Media_Other = models.CharField(max_length=100, null=True, blank=True)
    Created_By = models.CharField(max_length=30, null=True, blank=True)
    Changed_By = models.CharField(max_length=30, null=True, blank=True)
    created_Date = models.DateField(auto_now_add=True,null=True, blank=True)
    created_Time = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    Changed_Date = models.DateField(auto_now=True, null=True, blank=True)
    Changed_Time = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.First_Name