from django.db import models

# Create your models here.
import datetime

current_date = datetime.date.today()
current_time = datetime.datetime.now().time()


class UserData(models.Model):
    # CrowdId = models.CharField(max_length=8, primary_key=True)
    Group1 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group2 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group3 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group4 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group5 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group6 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group7 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group8 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group9 = models.CharField(max_length=12, null=True, blank=True,default='')
    Group10 = models.CharField(max_length=12, null=True, blank=True,default='')
    Salutation = models.CharField(max_length=4, null=True, blank=True,default='')
    First_Name = models.CharField(max_length=40, null=True, blank=True,default='')
    Middle_Name = models.CharField(max_length=40, null=True, blank=True,default='')
    Last_Name = models.CharField(max_length=40, null=True, blank=True,default='')
    Primary_Number = models.CharField(max_length=20, null=True, blank=True,default='')
    Alternate_Number = models.CharField(max_length=20, null=True, blank=True,default='')
    Primary_Mail = models.CharField(max_length=80, null=True, blank=True,default='')
    Alternate_Mail = models.CharField(max_length=80, null=True, blank=True,default='')
    Location = models.CharField(max_length=30, null=True, blank=True,default='')
    City = models.CharField(max_length=30, null=True, blank=True,default='')
    State = models.CharField(max_length=30, null=True, blank=True,default='')
    Country = models.CharField(max_length=30, null=True, blank=True,default='')
    Pincode = models.CharField(max_length=8, null=True, blank=True,default='')
    Designation = models.CharField(max_length=40, null=True, blank=True,default='')
    Primary_Expertise = models.CharField(max_length=30, null=True, blank=True,default='')
    Primary_Expertise1 = models.CharField(max_length=30, null=True, blank=True,default='')
    Primary_Expertise2 = models.CharField(max_length=30, null=True, blank=True,default='')
    Highest_Education = models.CharField(max_length=40, null=True, blank=True,default='')
    Gender = models.CharField(max_length=6, null=True, blank=True,default='')
    DOB = models.CharField(max_length=6,null=True, blank=True,default='')
    Message_Open = models.CharField(max_length=1, null=True, blank=True,default='')
    Responded = models.CharField(max_length=1, null=True, blank=True,default='')
    Linked_Clicked = models.CharField(max_length=1, null=True, blank=True,default='')
    Source = models.CharField(max_length=30, null=True, blank=True,default='')
    Org_Name = models.CharField(max_length=40, null=True, blank=True,default='')
    Nature_Of_Business = models.CharField(max_length=120, null=True, blank=True,default='')
    Org_Name_Location = models.CharField(max_length=20, null=True, blank=True,default='')
    Do_Not_Call = models.CharField(max_length=1, null=True, blank=True,default='')
    Do_Not_Message = models.CharField(max_length=1, null=True, blank=True,default='')
    Do_Not_Mail = models.CharField(max_length=1, null=True, blank=True,default='')
    Do_Not_Whatsapp = models.CharField(max_length=1, null=True, blank=True,default='')
    Do_Not_Disturb = models.CharField(max_length=1, null=True, blank=True,default='')
    Notes1 = models.CharField(max_length=120, null=True, blank=True,default='')
    Notes2 = models.CharField(max_length=120, null=True, blank=True,default='')
    Notes3 = models.CharField(max_length=120, null=True, blank=True,default='')
    Notes4 = models.CharField(max_length=120, null=True, blank=True,default='')
    Notes5 = models.CharField(max_length=120, null=True, blank=True,default='')
    Remarks = models.CharField(max_length=500, null=True, blank=True,default='')
    Document_Attach = models.ImageField(upload_to='DocumentAttach/', null=True, blank=True)
    Called = models.CharField(max_length=1, null=True, blank=True,default='')
    Met = models.CharField(max_length=1, null=True, blank=True,default='')
    Full_Name = models.CharField(max_length=100, null=True, blank=True,default='')
    Out_Of_Station = models.CharField(max_length=1, null=True, blank=True,default='')
    Out_Of_Country = models.CharField(max_length=1, null=True, blank=True,default='')
    Generated_Pincode = models.CharField(max_length=8, null=True, blank=True,default='')
    Mark_For_Deletion = models.CharField(max_length=1, null=True, blank=True,default='')
    Reason_For_Deletion = models.CharField(max_length=30, null=True, blank=True,default='')
    Blog_Link = models.CharField(max_length=100, null=True, blank=True,default='')
    Website = models.CharField(max_length=100, null=True, blank=True,default='')
    Linkedin_Link = models.CharField(max_length=100, null=True, blank=True,default='')
    Instagram_Link = models.CharField(max_length=100, null=True, blank=True,default='')
    Youtube_Link = models.CharField(max_length=100, null=True, blank=True,default='')
    Facebook_Link = models.CharField(max_length=100, null=True, blank=True,default='')
    Social_Media_Other = models.CharField(max_length=100, null=True, blank=True,default='')
    Created_By = models.CharField(max_length=30, null=True, blank=True,default='')
    Changed_By = models.CharField(max_length=30, null=True, blank=True,default='')
    Entered_By = models.CharField(max_length=30, null=True, blank=True,default='')
    created_Date = models.CharField(max_length=30,null=True, blank=True, default=current_date.strftime('%Y-%m-%d'))
    created_Time = models.CharField(max_length=30,default=current_time.strftime("%H:%M:%S"),null=True, blank=True)
    Changed_Date = models.CharField(max_length=30,null=True, blank=True,default='')
    Changed_Time = models.CharField(max_length=30,null=True, blank=True,default='')

    def __str__(self):
        return self.First_Name